version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-test-common
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-test
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-reflect
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-test-junit
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
  - dependency-name: org.junit.jupiter:junit-jupiter
    versions:
    - 5.7.0
    - 5.7.1
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - 1.4.2-native-mt
  - dependency-name: org.ow2.asm:asm-analysis
    versions:
    - "9.0"
  - dependency-name: org.ow2.asm:asm
    versions:
    - "9.0"
  - dependency-name: org.ow2.asm:asm-tree
    versions:
    - "9.0"
