name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test gradle build      
      run: |
        gradle processTestResources
        gradle build
        gradle test
        gradle build
        gradle jacocoTestReport
        gradle jacocoTestCoverageVerification
    - name: Update Coverage    
      uses: codecov/codecov-action@v1
      with: 
        token: ${{ secrets.CODECOV_TOKEN }} 
